#!/bin/sh

testbench="CPU_tb.cpp"

if [ $# -eq 1 ]; then
  if [ -f ../programs/$1.s ]; then
    echo "Assembling $1.s from programs"
    cd ../assembler
    ./assemble.sh $1
    echo "Deleting old program, and loading $1.mem into CPU."
    cd ../RTL/CPU
    rm -f instruction.mem
    cp ../../programs/$1.mem instruction.mem
    rm -f ../../programs/$1.mem
  else
    echo "File does not exist in the programs folder!"
  fi
elif [ $# -eq 2 ]; then # passing aasembly file and testbench
  if [ -f ../programs/$1.s ]; then
    echo "Assembling $1.s from programs"
    cd ../assembler
    ./assemble.sh $1
    echo "Deleting old program, and loading $1.mem into CPU."
    cd ../RTL/CPU
    rm -f instruction.mem
    cp ../../programs/$1.mem instruction.mem
    rm -f ../../programs/$1.mem
  else
    echo "File does not exist in the programs folder!"
  fi
  if [ -f ../../programs/$2.cpp ]; then
    echo "Using $2.cpp as testbench"
    cp ../../programs/$2.cpp tmp_tb.cpp
    testbench=tmp_tb.cpp
  else
    echo "Testbench file not found, using default CPU_tb.cpp"
  fi
elif [ $# -eq 3 ]; then # passing aasembly file and testbench
  if [ -f ../programs/$1.s ]; then
    echo "Assembling $1.s from programs"
    cd ../assembler
    ./assemble.sh $1
    echo "Deleting old program, and loading $1.mem into CPU."
    cd ../RTL/CPU
    rm -f instruction.mem
    cp ../../programs/$1.mem instruction.mem
    rm -f ../../programs/$1.mem
  else
    echo "File does not exist in the programs folder!"
  fi
  if [ -f ../../programs/$2.cpp ]; then
    echo "Using $2.cpp as testbench"
    cp ../../programs/$2.cpp tmp_tb.cpp
    testbench=tmp_tb.cpp
  else
    echo "Testbench file not found, using default CPU_tb.cpp"
  fi

  if [ -f ../../programs/$3.mem ]; then
    rm -f data.mem
    cp ../../programs/$3.mem data.mem
  else 
    echo "Data mem $3.mem not found"
  fi
elif [ $# -eq 0 ]; then
  echo "Running previous program!"
  cd CPU/
else
  echo "Expected one or two parameters!"
  exit 
fi


# cleanup
rm -rf obj_dir
rm -f *.vcd

# run Verilator to translate Verilog into C++, including C++ testbench
if ! verilator --Wall --cc --trace ../TYPES/types_pkg.sv CPU.sv -I../CONTROL_UNIT -I../DATA_MEMORY -I../SIGN_EXTEND -I../PC -I../REGFILE_ALU/REGFILE -I../REGFILE_ALU/ALU -I../DECODE_EXECUTE_REGISTER -I../EXECUTE_MEMORY_REGISTER -I../FETCH_DECODE_REGISTER -I../MEMORY_WRITEBACK_REGISTER --top-module CPU --exe $testbench; then
  cd ../
  echo "VERILATOR COMPILATION FAILED!"
else # success
  # build C++ project via make automatically generated by Verilator
  make -j -C obj_dir/ -f VCPU.mk VCPU > /dev/null

  if [ -f ./tmp_tb.cpp ]; then 
    echo "removing tb file"
    rm -f tmp_tb.cpp
  fi

  # run executable simulation file
  echo "Running simulation"
  obj_dir/VCPU > out.txt
  
  cat out.txt

  if ! cat out.txt | grep -q "Error"; then
    echo "Simulation completed"

    echo "Caculating hitrate!"
    cd ../../assembler
    python3 hitcal.py
    cd ../RTL


    rm CPU/out.txt
  else
    echo "Error occured!"
    rm out.txt
    cd ../
  fi
fi