#!/bin/sh

# cleanup
rm -rf obj_dir
rm -f *.vcd

# run Verilator to translate Verilog into C++, including C++ testbench
verilator -Wall --cc --trace ../TYPES/types_pkg.sv SIGN_EXTEND.sv --top-module SIGN_EXTEND --exe SIGN_EXTEND_tb.cpp

# build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f VSIGN_EXTEND.mk VSIGN_EXTEND

# run executable simulation file
echo "\nRunning simulation"
obj_dir/VSIGN_EXTEND
echo "\nSimulation completed"

