# Fail on error or unbounded variable
set -euo pipefail

# cleanup
rm -rf obj_dir
rm -f out.vcd

# run Verilator to trnanslate Verilog into C++, incuding the C++ testbench
verilator -Wall --cc --trace REGFILE_ALU.sv --exe REGFILE_ALU_tb.cpp

# Build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f VREGFILE_ALU.mk VREGFILE_ALU

# run exec
obj_dir/VREGFILE_ALU
