#!/bin/sh

# cleanup
rm -rf obj_dir
rm -f *.vcd

# run Verilator to translate Verilog into C++, including C++ testbench
verilator --cc --trace ../TYPES/types_pkg.sv RAM.sv --top-module RAM --exe RAM_tb.cpp

# build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f VRAM.mk VRAM

# run executable simulation file
echo "\nRunning simulation"
obj_dir/VRAM
echo "\nSimulation completed"

