#!/bin/sh

# cleanup
rm -rf obj_dir
rm -f *.vcd

# run Verilator to translate Verilog into C++, including C++ testbench
verilator --cc --trace ../TYPES/types_pkg.sv DATA_MEMORY.sv --top-module DATA_MEMORY --exe DATA_MEMORY_tb.cpp

# build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f VDATA_MEMORY.mk VDATA_MEMORY

# run executable simulation file
echo "\nRunning simulation"
obj_dir/VDATA_MEMORY
echo "\nSimulation completed"

