#!/bin/sh

# cleanup
rm -rf obj_dir
rm -f *.vcd

# run Verilator to translate Verilog into C++, including C++ testbench
verilator -Wall --cc --trace ../TYPES/types_pkg.sv PC_ROM.sv --top-module PC_ROM --exe PC_ROM_tb.cpp

# build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f VPC_ROM.mk VPC_ROM

# run executable simulation file
echo "\nRunning simulation"
obj_dir/VPC_ROM
echo "\nSimulation completed"

