#!/bin/sh

# cleanup
rm -rf obj_dir
rm -f *.vcd

# run Verilator to translate Verilog into C++, including C++ testbench
verilator -Wall --cc --trace ../TYPES/types_pkg.sv sign_extend.sv --top-module sign_extend --exe sign_extend_tb.cpp

# build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vsign_extend.mk Vsign_extend

# run executable simulation file
echo "\nRunning simulation"
obj_dir/Vsign_extend
echo "\nSimulation completed"

