# Fail on error or unbounded variable
set -euo pipefail

# cleanup
rm -rf obj_dir
rm -f ALU.vcd

# run Verilator to translate Verilog into C++, incuding the C++ testbench
verilator -Wall --cc --trace ../../TYPES/types_pkg.sv ALU.sv --top-module ALU --exe ALU_tb.cpp

# Build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f VALU.mk VALU

# run exec
obj_dir/VALU
