#!/bin/sh

# cleanup
rm -rf obj_dir
rm -f *.vcd

# run Verilator to translate Verilog into C++, including C++ testbench
verilator -Wall --cc --trace ../TYPES/types_pkg.sv CONTROL_UNIT.sv --top-module CONTROL_UNIT --exe control_unit_tb.cpp

# build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f VCONTROL_UNIT.mk VCONTROL_UNIT

# run executable simulation file
echo "Running simulation"
obj_dir/VCONTROL_UNIT
echo "Simulation completed"

