# Fail on error or unbounded variable
set -euo pipefail

# cleanup
rm -rf obj_dir
rm -f REGFILE.vcd

# run Verilator to translate Verilog into C++, incuding the C++ testbench
verilator -Wall --cc --trace ../../TYPES/types_pkg.sv REGFILE.sv --top-module REGFILE --exe REGFILE_tb.cpp

# Build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f VREGFILE.mk VREGFILE

# run exec
obj_dir/VREGFILE
