name: Push to Cheung

on:
  push
  
jobs:
  pushToCheung:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Push to P. Cheung's repo
        env:
           token: ${{ secrets.DIEGO_PAT }}
        run: |
          git config -l | grep 'http\..*\.extraheader' | cut -d= -f1 | xargs -L1 git config --unset-all
          git push --mirror https://token:$token@github.com/EIE2-IAC-Labs/iac-riscv-cw-5.git
        
