name: Push to Cheung

on:
  push
  
jobs:
  pushToCheung:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository, including all refs by using --mirror
        env:
           token: ${{ secrets.DIEGO_PAT }}
        run: git clone --bare https://token:$token@github.com/EZePiZy/RISC-V-CPU.git riscv-repo
      - name: Remove this workflow from mirror and push to P. Cheung's repo
        env:
           token: ${{ secrets.DIEGO_PAT }}
        run: |
          cd riscv-repo
          rm -rf .github
          git push --mirror https://token:$token@github.com/EIE2-IAC-Labs/iac-riscv-cw-5.git
        
